"""add visa-application status column to the travellers table

Revision ID: 39e743924380
Revises: 5509a045a5c5
Create Date: 2023-12-28 16:57:05.390426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e743924380'
down_revision: Union[str, None] = '5509a045a5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travellers', sa.Column('visa_application_status', sa.String(), nullable=True, default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travellers', 'visa_application_status')
    # ### end Alembic commands ###
