"""add staying_status column to the travellers table

Revision ID: 5509a045a5c5
Revises: f7311c27a2bb
Create Date: 2023-12-27 13:56:52.816785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5509a045a5c5'
down_revision: Union[str, None] = 'f7311c27a2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travellers', sa.Column('staying_status', sa.String(), nullable=True,default="stay"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travellers', 'staying_status')
    # ### end Alembic commands ###
