"""change country column to alpha3_country_code and add a new column country

Revision ID: a95090aeda27
Revises: 39e743924380
Create Date: 2024-01-02 11:01:27.122159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95090aeda27'
down_revision: Union[str, None] = '39e743924380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travellers', sa.Column('alpha3_country_code', sa.String(), nullable=True,default=""))
    #change nullable to True in country column
    op.alter_column('travellers', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travellers', 'alpha3_country_code')
    #change nullable to False in country column
    op.alter_column('travellers', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    pass
