"""create travellers table

Revision ID: c09742ec6dd0
Revises: c93d794af460
Create Date: 2023-12-24 16:49:16.301489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09742ec6dd0'
down_revision: Union[str, None] = 'c93d794af460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('mrz_type', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('passport_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('passport_expiration_date', sa.String(), nullable=False),
    sa.Column('personal_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.TIMESTAMP(timezone=True), nullable=False,default=sa.text('now()')),
    sa.Column('expiry_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ticket_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travellers')
    # ### end Alembic commands ###
