"""add status column to travellers table

Revision ID: f7311c27a2bb
Revises: dd4f37a1e918
Create Date: 2023-12-27 12:57:27.084938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7311c27a2bb'
down_revision: Union[str, None] = 'dd4f37a1e918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travellers', sa.Column('status', sa.String(), nullable=True, default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travellers', 'status')
    # ### end Alembic commands ###
